### ISSUE TITLE
how can i solve this problom

### ISSUE THREAD

**Issue by occultcoedx** [docwza/sumolights#11]
when  run this program, the sumo-gui will stop sharply and pycharm will throw the problem in this picture

![image](https://user-images.githubusercontent.com/42198565/81493617-7876e000-92d4-11ea-9176-761872c62a46.png)

**Comment by HappyDay-design** [comment]
> when run this program, the sumo-gui will stop sharply and pycharm will throw the problem in this picture
> 
> ![image](https://user-images.githubusercontent.com/42198565/81493617-7876e000-92d4-11ea-9176-761872c62a46.png)

Hello. I have the same error.
How did you fix it?
