### ISSUE TITLE
After ran python graph_results.py, lack of  dqn method figure.

### ISSUE THREAD

**Issue by yuy01** [docwza/sumolights#16]
After i ran the steps above, then Visualize results with: python graph_results.py, there are four methods, lack of the dqn method, and the "metrics" folder also lack of dqn folder.

**Comment by moragab1993** [comment]
i faced the same issue

running the test command for dqn only found in `gen_results.sh` :
     `python run.py -sim double -n 8 -tsc dqn -load -nogui -mode test`

i got this error

```
Traceback (most recent call last):
  File "/home/med/anaconda3/envs/sumolight/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/media/med/work/sumolights/src/simproc.py", line 45, in run
    self.args.n_hidden)
  File "/media/med/work/sumolights/src/nn_factory.py", line 95, in gen_neural_networks
    neural_nets[tsc].load_weights(path)
  File "/media/med/work/sumolights/src/neuralnets/dqn.py", line 54, in load_weights
    self.models['online'].load_weights(path)
  File "/home/med/anaconda3/envs/sumolight/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/med/anaconda3/envs/sumolight/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/home/med/anaconda3/envs/sumolight/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 711, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```
the way i solved it is 
`pip install h5py==2.10.0`

and i managed to see dqn in the graph

**Comment by HappyDay-design** [comment]
> After i ran the steps above, then Visualize results with: python graph_results.py, there are four methods, lack of the dqn method, and the "metrics" folder also lack of dqn folder.

After training and testing model, I had full results as instructions

**Comment by yuy01** [comment]
你好，邮件已收到。这是来自QQ邮箱的自动回复邮件。

**Comment by ShenZC25** [comment]
> After i ran the steps above, then Visualize results with: python graph_results.py, there are four methods, lack of the dqn method, and the "metrics" folder also lack of dqn folder.

Hello, have you solved this problem? I haven't seen the folder of DQN either.Can we add QQ to discuss?

**Comment by docwza** [comment]
Is this issue still active or did the following two comments fix people's issues?

> i faced the same issue
> 
> running the test command for dqn only found in `gen_results.sh` : `python run.py -sim double -n 8 -tsc dqn -load -nogui -mode test`
> 
> i got this error
> 
> ```
> Traceback (most recent call last):
>   File "/home/med/anaconda3/envs/sumolight/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/media/med/work/sumolights/src/simproc.py", line 45, in run
>     self.args.n_hidden)
>   File "/media/med/work/sumolights/src/nn_factory.py", line 95, in gen_neural_networks
>     neural_nets[tsc].load_weights(path)
>   File "/media/med/work/sumolights/src/neuralnets/dqn.py", line 54, in load_weights
>     self.models['online'].load_weights(path)
>   File "/home/med/anaconda3/envs/sumolight/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
>     return super(Model, self).load_weights(filepath, by_name)
>   File "/home/med/anaconda3/envs/sumolight/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
>     saving.load_weights_from_hdf5_group(f, self.layers)
>   File "/home/med/anaconda3/envs/sumolight/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 711, in load_weights_from_hdf5_group
>     original_keras_version = f.attrs['keras_version'].decode('utf8')
> AttributeError: 'str' object has no attribute 'decode'
> ```
> 
> the way i solved it is `pip install h5py==2.10.0`
> 
> and i managed to see dqn in the graph



> > After i ran the steps above, then Visualize results with: python graph_results.py, there are four methods, lack of the dqn method, and the "metrics" folder also lack of dqn folder.
> 
> After training and testing model, I had full results as instructions

**Comment by yuy01** [comment]
你好，邮件已收到。这是来自QQ邮箱的自动回复邮件。

**Comment by yuy01** [comment]
你好，邮件已收到。这是来自QQ邮箱的自动回复邮件。
