### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zzchuman** [docwza/sumolights#2]
hello,may i  ask you a questionn?  
i run your program by windows cmd. But, it appears a bug:
![image](https://user-images.githubusercontent.com/38434094/64699776-1c0ab900-d4d8-11e9-9684-8271095e1eb6.png)
Can you look it? 
Thank you!
 Best Wishes!

**Comment by docwza** [comment]
As you experienced, there was an issue with Windows where an error was thrown with the time in the file name. I have made a commit that prevents the error, I tested it on my local Windows and it seems to work - let me know if it works for you.

**Comment by zzchuman** [comment]
Now the program is working properly. Thank you for your timely reply.
Best Wishes!!
