### ISSUE TITLE
after running train_ddpg.sh

### ISSUE THREAD

**Issue by ShengChee98** [docwza/sumolights#24]
learner waiting at barrier ------------
learner proc 0 waiting at offset barrier------------
learner proc 0 broken offset barrier ------------
![Screenshot from 2022-05-25 16-14-31](https://user-images.githubusercontent.com/86827348/170214801-4b4f7de2-b9ca-4f11-a746-8977457b77ce.png)

**Comment by ShengChee98** [comment]
Can someone explain what is happening here, there is no changes after one day running this code

**Comment by docwza** [comment]
Hi ShengChee98,

Are you still facing this issue?
