### ISSUE TITLE
There is no modification program, but the running result is different from the source program.

### ISSUE THREAD

**Issue by ShenZC25** [docwza/sumolights#26]
Dear Wade, there are some questions about the program.

1. After I ran' pythongraph _ results.py', I found that the error of DQN' distribution of travel times' in box graph was very large (the abnormal value of DQN reached more than 2,000, while SOTL was only about 1,500). I haven't adjusted any parameters. After several training sessions, it's all the same. Excuse me, what is the reason for this?
![Question_1](https://user-images.githubusercontent.com/89288084/177001260-a6171a7d-a6ee-4dad-bbbc-b9fa468655ff.png)

2. In addition, again, no parameters have been modified. After I run' python graph _ results.py', the values of' Queue' are all smaller than the source program (for example, the peak value is only 1500, while the source program exceeds 8000), while the values of' Delay' are consistent with the results of the source program. Excuse me, what is the reason for this?There is no modification program, but the running result is different from the source program.
![Question_2](https://user-images.githubusercontent.com/89288084/177001254-5b6c4716-8e96-4138-b957-cef648382bbb.png)

**Comment by docwza** [comment]
Hey ShenZC25,

It is difficult to say why the DQN's performance is so different, my guess is that the DQN's policy is not converging for some reason. Have you tried running SUMO with the GUI and observing the DQN's policy after training? It may yield some insights. 

The performance difference could also be caused by a difference in library versions, which version of tensorflow are you using? If I recall correctly when I performed this work a few years ago I was using tensorflow 1.8. If you are using a different version of tensorflow, try using this version.

**Comment by HappyDay-design** [comment]
> Hey ShenZC25,
> 
> It is difficult to say why the DQN's performance is so different, my guess is that the DQN's policy is not converging for some reason. Have you tried running SUMO with the GUI and observing the DQN's policy after training? It may yield some insights.
> 
> The performance difference could also be caused by a difference in library versions, which version of tensorflow are you using? If I recall correctly when I performed this work a few years ago I was using tensorflow 1.8. If you are using a different version of tensorflow, try using this version.

Hello. You did not show a reward graph over episodes so I do not know the convergence of DQN and DDPG. It is better to know the performance of the 2 models

**Comment by ShenZC25** [comment]
> Hey ShenZC25,
> 
> It is difficult to say why the DQN's performance is so different, my guess is that the DQN's policy is not converging for some reason. Have you tried running SUMO with the GUI and observing the DQN's policy after training? It may yield some insights.
> 
> The performance difference could also be caused by a difference in library versions, which version of tensorflow are you using? If I recall correctly when I performed this work a few years ago I was using tensorflow 1.8. If you are using a different version of tensorflow, try using this version.

Hi Wade,
Thank you very much for your kind answer.

When I set the option to open the interface of running SUMO GUI for training, my computer didn't know why it stopped training, so I couldn't open the GUI for observation, and as another friend said, maybe the program didn't have a reward chart.

I installed' tensorflow 1.14.0' according to the' requirements.txt' file, but the program seems to be written in' tensorflow 2.X', because a lot of syntax in the program is the content of' tensorflow 2.X'. I installed' tensorflow 1.14.0' and running it directly will report an error that some syntax has been abandoned. So I'll try reinstalling' tensorflow 1.8' now. If there is any problem, I'll consult and communicate later.
