### ISSUE TITLE
How to import real traffic data

### ISSUE THREAD

**Issue by locker2153** [docwza/sumolights#27]
Hello,docwza. I have some real traffic data here. I want to use the rou.xml file of sumo as the vehicle input. Is this feasible. Can I complete my requirements by modifying file vehiclegen

**Comment by docwza** [comment]
Yes it is possible but you do not need to modify vehiclegen. You need to do the following:

- add the rou.xml to the *.sumocfg file
- the vehiclegen code only runs for the single or double network. If you are using either of those networks with your route.xml, comment out the creation of the VehicleGen object in the sumosim.py around line 48. If you are using another network with a different name vehiclegen should not run.
