### ISSUE TITLE
How to write such a beautiful code

### ISSUE THREAD

**Issue by MeixinZhu** [docwza/sumolights#3]
This is not an issue. First of all, wonderful work. Second, as a Civil student, I use python but just want to know how I can learn to write code well structured like yours (e.g., define folders, define classes). Could you provide some resources for me to learn to code professionally?

**Comment by docwza** [comment]
Like any skill, to improve your programming capabilities you must practice. The more you program the better programmer you will become. Think of software that would be useful to you and then attempt to implement it yourself. It will likely not work and contain errors but understand this is what every programmer goes through. If you have no background or formal software development experience, I would suggest consulting the following content, some of which are broad concepts and ideas while others are specific techniques or tools.

[Object-oriented programming](https://en.wikipedia.org/wiki/Object-oriented_programming) is a programming paradigm that develops code using entities known as objects. I find it a useful way to structure my code and used OO ideas a lot in this repository. After familiarizing yourself with object-oriented programming, you can also study [design patterns
](https://en.wikipedia.org/wiki/Software_design_pattern)

[Separation of Concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) is a high-level design principle that states that your code should be modular and each software component should only address one concern. 

Any problem you have faced has likely been solved on [Stackoverflow](https://stackoverflow.com/) learn to consult this regularly for advice. However, it is worth struggling to solve a problem by yourself first before you seek help, as this is how you will grow.

Other general tips are to never write the same code twice (i.e., encapsulate useful code in functions and call the functions wherever necessary), write short functions, comment your code, learn to use version control software like git and automated testing to preserve your sanity.

**Comment by MeixinZhu** [comment]
Hi Wade. I really appreciate your helpful suggestions. Thanks a lot !!!

**Comment by occultcoedx** [comment]
> This is not an issue. First of all, wonderful work. Second, as a Civil student, I use python but just want to know how I can learn to write code well structured like yours (e.g., define folders, define classes). Could you provide some resources for me to learn to code professionally?

hello, there are some questions when i run this program, may i contact you and ask you some questions about this program. please contact me by 710448010@qq.com. 
thank you 
best wishes.
