### ISSUE TITLE
How to display on the Sumo-gui

### ISSUE THREAD

**Issue by wsz1998** [docwza/sumolights#30]
Hello, could you tell me how to display on the Sumo-gui.I don't know how to modify these code to realize it.
I'm looking forward to your reply.

**Comment by docwza** [comment]
First you need to ensure that you have installed SUMO with gui capabilities which depends on your operating system, [consult the developers installation docs](https://sumo.dlr.de/docs/Installing/index.html).

Once you have installed SUMO with gui capabilities, to run with the gui use the following command-line arguments:

`-n 1 -mode test`

Note however, to work with the RL controllers, you must first run `-mode train` and then test with loading the trained weights `-n 1 -mode test -load`.
