### ISSUE TITLE
Fixed Time Traffic Light parameters

### ISSUE THREAD

**Issue by indranilmaji** [docwza/sumolights#31]
Hello, 

I would like to know whether the green_phase/yellow_phase duration in the fixed time traffic light was same as the action repeat duration in the RL based approaches.

Thank you.

**Comment by docwza** [comment]
The [yellow_phase](https://github.com/docwza/sumolights/blob/62a4f4cecd5a10555e40e53afd91156139b0fe1e/src/argparse.py#L26) durations default to the values declared in the command line argument for all traffic signal controllers.

The [green_phase](https://github.com/docwza/sumolights/blob/62a4f4cecd5a10555e40e53afd91156139b0fe1e/src/argparse.py#L25) duration command line argument is the same for the fixed time traffic light and [DQN-based RL controller](https://github.com/docwza/sumolights/blob/master/src/trafficsignalcontrollers/nextphaserltsc.py).

However, the DDPG based controller's action selection dictates the duration of the next green phase.
