### ISSUE TITLE
node_id == '-13968'

### ISSUE THREAD

**Issue by shengchao-y** [docwza/sumolights#9]
Hi Dr. Genders,

thanks for the great framework!
I could not understand the code "[node_id == '-13968'](https://github.com/docwza/sumolights/blob/a2bb89e29d822dcde8aa1fe7a9dc9c48f818a4fc/src/networkdata.py#L129)" in networkdata.py. Where does this number come from? Why do you handle it with some extra code?

Best,

**Comment by docwza** [comment]
This was erroneously left over from a previous repo, I will remove it.
